<footer>
    <p>&copy; Leetfeed <?php echo date('Y') ?>
        <a href="http://www.facebook.com/leetfeed" target="_blank"><img
                src="<?php echo $this->basePath('images/fb-icon-24x24.png'); ?>"/></a>
        <a href="http://www.twitter.com/leetfeed" target="_blank"><img
                src="<?php echo $this->basePath('images/twitter-icon-24x24.png'); ?>"/></a></p>
    <nav>
        <ul>
            <li><a href="<?php echo $this->url("faq"); ?>">FAQ</a></li>
            <li><a href="<?php echo $this->url("promote"); ?>">Promote</a></li>
            <li><a href="<?php echo $this->url("contact"); ?>">Contact</a></li>
        </ul>
    </nav>
</footer>
<?php
$this->inlineScript()->prependFile($this->basePath('js/main-1.0.0.min.js'), 'text/javascript')
    ->prependFile($this->basePath('js/lib.min.js'))
    ->prependFile($this->basePath('js/jquery.mousewheel.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/perfect-scrollbar.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/jquery-1.11.0.min.js', 'text/javascript'));

if (isset($this->child->includeProgressBar)) {
    $this->inlineScript()->appendFile($this->basePath('js/progress.min.js', 'text/javascript'));
}
if (isset($this->child->includeAjaxForm)) {
    $this->inlineScript()->appendFile($this->basePath('js/jquery.form.min.js', 'text/javascript'));
}
echo $this->inlineScript();
?>
<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=268335233334900";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>