<head>
    <?php
    $child = $this->child;
    $isMobile = $this->mobile();
    $pageTitle = (isset($child->pageTitle)) ? $child->pageTitle : "Leetfeed | League of Legends Videos, Gameplay, Tutorials";
    $follow = (isset($child->follow)) ? "noindex, nofollow" : "feed, follow, archieve";

    // The website's title.
    echo $this->headTitle($pageTitle);

    // The meta tags
    $description = isset($child->metaInfo['description']) ? $child->metaInfo['description'] : 'Leetfeed provides the best League of Legends gameplay, videos, tutorials and can help you improve.';
    $keywords = isset($child->metaInfo['keywords']) ? $child->metaInfo['keywords'] : 'league, of, legends, best, videos, gameplay, pro, players, funny, epic, leetfeed, youtube';

    // The og tags
    $ogTitle = isset($child->ogTags["title"]) ? $child->ogTags["title"] : "Leetfeed - The Best League of Legends videos.";
    $ogUrl = isset($child->ogTags["url"]) ? $child->ogTags["url"] : "http://www.leetfeed.com";
    $ogImage = isset($child->ogTags["image"]) ? $child->ogTags["image"] : "http://i.imgur.com/IMuF0ng.jpg";
    $ogDescription = isset($child->ogTags["description"]) ? $child->ogTags["description"] : $description;
    $ogType = isset($child->ogTags["type"]) ? $child->ogTags["type"] : "website";

    // We append everything to the headMeta
    $this->headMeta()
        ->setCharset('UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', $description)
        ->appendName('keywords', $keywords)
        ->appendName('robots', $follow)
        ->appendName('language', 'en')
        ->appendName('googlebot', $follow)
        ->appendProperty('fb:app_id', '268335233334900')
        ->appendProperty('fb:admins', '1124061431')
        ->appendProperty("og:site_name", "Leetfeed")
        ->appendProperty('og:title', $ogTitle)
        ->appendProperty('og:type', $ogType)
        ->appendProperty('og:url', $ogUrl)
        ->appendProperty('og:description', $ogDescription)
        ->appendProperty('og:image', $ogImage);

    // If there is a single video on the page, we add the specific og tags
    if ($child->ogTags["video"]) {
        $this->headMeta()
            ->appendProperty('og:video', $child->ogTags["video"])
            ->appendProperty('og:video:type', "application/x-shockwave-flash")
            ->appendProperty('og:video:width', "965")
            ->appendProperty('og:video:height', "576");
    }
    echo $this->headMeta();

    // We add the favicon and our stylesheets
    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('images/favicon.ico')))
        ->prependStylesheet($this->basePath('css/style.min.css'));

    // Here are some page-specific stylesheets
    if (isset($child->includeProgressBar)) {
        $this->headLink()->prependStylesheet($this->basePath('css/ui.progress-bar.min.css'));
    }
    if ($isMobile) {
        $this->headLink()->appendStylesheet($this->basePath('css/mobile.min.css'));
    }
    echo $this->headLink();

    // Some scripts the must be outputted first follow below
    ?>
    <script>
        var baseUrl = '<?php echo $this->basePath(); ?>';
        var isMobile = <?php echo $isMobile ? 'true':'false'; ?>;
    </script>
    <script type="text/javascript" async="async" src="http://www.google-analytics.com/ga.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-48935331-1', 'leetfeed.com');
        ga('send', 'pageview');

    </script>
</head>