<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Feed\Module'                       => __DIR__ . '/Module.php',
  'Feed\Controller\CommentController' => __DIR__ . '/src/Feed/Controller/CommentController.php',
  'Feed\Controller\FeedController'    => __DIR__ . '/src/Feed/Controller/FeedController.php',
  'Feed\Entity\Comment'               => __DIR__ . '/src/Feed/Entity/Comment.php',
  'Feed\Entity\Feed'                  => __DIR__ . '/src/Feed/Entity/Feed.php',
  'Feed\Entity\Game'                  => __DIR__ . '/src/Feed/Entity/Game.php',
  'Feed\Entity\PremiumFeed'           => __DIR__ . '/src/Feed/Entity/PremiumFeed.php',
  'Feed\Entity\Rating'                => __DIR__ . '/src/Feed/Entity/Rating.php',
  'Feed\Entity\Youtuber'              => __DIR__ . '/src/Feed/Entity/Youtuber.php',
  'Feed\Factory\AddFeedFormFactory'   => __DIR__ . '/src/Feed/Factory/AddFeedFormFactory.php',
  'Feed\Form\AddFeedFieldset'         => __DIR__ . '/src/Feed/Form/AddFeedFieldset.php',
  'Feed\Form\AddFeedForm'             => __DIR__ . '/src/Feed/Form/AddFeedForm.php',
  'Feed\Model\FeedGenerator'          => __DIR__ . '/src/Feed/Model/FeedGenerator.php',
  'Feed\Repository\FeedRepository'    => __DIR__ . '/src/Feed/Repository/FeedRepository.php',
  'Feed\Service\Comment'              => __DIR__ . '/src/Feed/Service/Comment.php',
  'Feed\Service\Feed'                 => __DIR__ . '/src/Feed/Service/Feed.php',
);
