<div id="main">
    <div id="register" class="module semiTransparentBackground">
        <h1>Register</h1>
        <img class="centeredImage" src="<?php echo $this->basePath() . '../images/leetfeed-medium.png'; ?>" alt="<?php echo $this->translate("Leetfeed Logo"); ?>"/>
        <p>It's really easy! Just fill in your username, password, email and you are ready to go!</p>
        <?php
        $form->prepare();
        $form->setAttribute('action', $this->url('account-register'));
        $fieldset = $form->get('account');

        echo $this->form()->openTag($form);
      #  echo $this->formHidden($form->get('security'));
        ?>
        <div class="element">
            <?php
            echo $this->formElementErrors($fieldset->get('username'), array('class' => 'formError'));
            echo $this->formLabel($fieldset->get('username'));
            echo $this->formInput($fieldset->get('username'));
            ?>
        </div>

        <div class="element">
            <?php
            echo $this->formElementErrors($fieldset->get('password'), array('class' => 'formError'));
            echo $this->formLabel($fieldset->get('password'));
            echo $this->formInput($fieldset->get('password'));
            ?>
        </div>

        <div class="element">
            <?php
            echo $this->formElementErrors($fieldset->get('email'), array('class' => 'formError'));
            echo $this->formLabel($fieldset->get('email'));
            echo $this->formInput($fieldset->get('email'));
            ?>
        </div>


        <div class="element">
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Register'))); ?>
        </div>

        <?php echo $this->form()->closeTag() ?>

        <p>Already have an account? Click <a href="<?php echo $this->url('account-login'); ?>">here to login</a></p>
    </div>
</div>