<div id="main">
    <div class="module halfSized">
        <div class="moduleBody">
            <h1><?php echo $this->translate('League of Legends Account Summoners'); ?></h1>
            <?php if ($summoners->count() > 0): ?>
                <ul class="summoners">
                    <?php foreach ($summoners as $summoner): ?>
                        <li class="summoner-<?php echo $summoner->getSummonerId(); ?>">
                            <a href="<?php echo $this->url('improve', array('summonerId' => $summoner->getSummonerId())); ?>"
                               title="League of Legends gameplay tutorials for <?php echo $summoner->getName(); ?>">
                                <div class="summonerBody">
                                    <span class="author"><?php echo $summoner->getName(); ?></span>
                                    <?php echo ' on ' . strtoupper($summoner->getRegion()); ?>
                                </div>
                                <div class="summonerChampions">
                                    Latest Played Champions:
                                    <?php
                                    $champions = $leagueService->getLatestChampions($summoner);
                                    if (!empty($champions)) {
                                        $championNames = join(' , ', $champions);
                                        echo '<span>' . $championNames . '</span>';
                                    } else {
                                        echo "None";
                                    }
                                    ?>
                                </div>
                            </a>

                            <div class="summonerMeta link" title="<?php echo $this->translate("Remove this summoner from your account"); ?>">Remove</div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <div class="empty"><?php echo $this->translate("You haven't added a <strong>League of Legends summoner</strong> to your account yet! Add one using the button
                    on the right."); ?>
                </div>
            <?php endif ?>
            <?php if ($summoners->count() < 10): ?>
                <div id="addSummonerToggle" class="link"><?php echo $this->translate("Add Summoner"); ?></div>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php if ($summoners->count() < 10): ?>
    <div id="addSummoner">
        <h2><?php echo $this->translate("Add a new League of Legends Summoner"); ?></h2>
        <p><?php echo $this->translate("Type the name and the region of the league of legends summoner you want to add!"); ?></p>
        <?php
        $form->prepare();
        $form->setAttribute('action', $this->url('account/summoners'));
        $fieldset = $form->get('summoner');

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('security'));
        ?>
        <div class="element">
            <?php
            echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
            echo $this->formLabel($fieldset->get('name'));
            echo $this->formInput($fieldset->get('name'));
            ?>
        </div>

        <div class="element">
            <?php
            echo $this->formElementErrors($fieldset->get('region'), array('class' => 'formError'));
            echo $this->formLabel($fieldset->get('region'));
            echo $this->formSelect($fieldset->get('region'));
            ?>
        </div>


        <div class="element">
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Submit'))); ?>
        </div>

        <?php echo $this->form()->closeTag() ?>
    </div>
<?php endif; ?>