<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                     => __DIR__ . '/Module.php',
  'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Factory\ContactFormFactory' => __DIR__ . '/src/Application/Factory/ContactFormFactory.php',
  'Application\Form\ContactFieldset'       => __DIR__ . '/src/Application/Form/ContactFieldset.php',
  'Application\Form\ContactForm'           => __DIR__ . '/src/Application/Form/ContactForm.php',
);
