<div id="main">
    <div class="module">
        <h1>Youtubers / Pros</h1>

        <div class="moduleBody">
            <ul id="youtubers">
                <?php foreach ($youtubers as $youtuber): ?>
                    <li<?php if ($randomYoutuber->getYoutuberId() == $youtuber->getYoutuberId()) echo ' class="active" ' ?>>
                        <img src="<?php echo $youtuber->getThumbnail(); ?>"/>
                        <span
                            class="youtuber-<?php echo $youtuber->getName(); ?>"><?php echo $youtuber->getIgName(); ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="module">
        <h1><?php echo $randomYoutuber->getIgName(); ?>'s Latest Feeds</h1>

        <div class="moduleBody">
            <?php if (count($feeds) > 0) { ?>
                <ul data-token="<?php echo $nextToken; ?>" class="verticalFeedList" id="youtubersFeeds">
                    <?php
                    $hasPrivileges = $this->account() ? $this->account()->hasSuperPrivileges() : false;
                    foreach ($feeds as $feed) {
                        echo $this->partial("feed", array('feed' => $feed, 'isPremium' => false, 'hasPrivileges' => $hasPrivileges));
                    }
                    ?>
                </ul>
            <?php } else { ?>
                No feeds were found.
            <?php } ?>
        </div>
    </div>
</div>