<div id="main">
    <div id="improve" class="module">
        <div class="moduleBody halfSized">
            <h1><?php echo $this->translate("Improve your League of Legends skills"); ?></h1>
            <p>Do you want to improve your <strong>League of Legends</strong> play skills and finally reach <strong>Challenger?</strong> <br/>
                One of the best ways is watching <strong>League of Legends tutorials</strong> and <strong>gameplay</strong> from Pro/LCS players <br/>
                based on the champions you play, so that you can learn more about the champions' mechanics,<br />
                how you should approach them and generally improve your knowledge of the game. <br/>
                Here you can easily get tons of <strong>League of Legends tutorials</strong> without having to waste time searching by yourself. <br/>
                Only in <strong>2 steps.</strong><br/>
            </p>

            <h2>Step 1: Register an Account</h2>
            <p>It's easy. It's free. No validations or anything are required, just <a
                    href="<?php echo $this->url('register'); ?>" target="_blank">click here</a> fill in a username, password and email
                and you're ready!</p>
            <img src="<?php echo $this->basePath('images/register.jpg'); ?>" alt="<?php echo $this->translate("register form preview"); ?>" width="402" height="238"/>
            <h2>Step 2: Link your Summoners</h2>
            <p>After you register, <a href="<?php echo $this->url('account/summoners'); ?>" target="_blank">click here</a> and link your summoners by pressing on the add button as shown below.<br/>
            No worries, we don't need any passwords just the username and the region :)</p>
            <img src="<?php echo $this->basePath('images/add-summoners.jpg'); ?>" alt="<?php echo $this->translate("add summoner form preview"); ?>" width="402" height="238"/>
            <h2>Done!</h2>
            <p>You can now refresh this page or click on one of the summoners you added, and we will provide you with <strong>League of Legends tutorials</strong> based on the latest champions you played</p>
            <img src="<?php echo $this->basePath('images/improve.jpg'); ?>" alt="<?php echo $this->translate("tutorial list preview"); ?>" width="600" height="403"/>
        </div>
    </div>
</div>
