<div id="main">
    <div id="history" class="module">
        <h1>Leet'ed Feeds</h1>

        <div class="moduleBody">
            <?php if (count($feeds) > 0) { ?>
                <ul class="verticalFeedList">
                    <?php
                    $hasPrivileges = $this->account() ? $this->account()->hasSuperPrivileges() : false;
                    foreach ($feeds as $feed) {
                        echo $this->partial("feed", array('feed' => $feed, 'isPremium' => false, 'hasPrivileges' => $hasPrivileges));
                    }
                    ?>
                </ul>
            <?php } else { ?>
                <p>You haven't leet'ed any feeds yet.</p>
            <?php } ?>
        </div>
    </div>
</div>
