<div id="main">
    <div id="random" class="module">
        <h1>Generating Random Feed</h1>
        <p>Generating something unique, it's worth the patience!</p>
        <div id="progress_bar" class="ui-progress-bar ui-container halfSized">
            <div class="ui-progress" style="width: 79%;">
                <span class="ui-label" style="display:none;">Generating <b class="value">100%</b></span>
            </div>
        </div>
    </div>
</div>
