<?php
/**
 * @var $feed \Feed\Entity\Feed
 */
$id = $feed->getVideoId();
$feedId = $feed->getFeedId();
$author = $feed->getAuthor();
$comments = $feed->getComments();
$title = strlen($feed->getTitle()) >= 50 ? substr($feed->getTitle(), 0, 50) . '..' : $feed->getTitle();
$hasPrivileges = $this->account() ? $this->account()->hasSuperPrivileges() : false;
?>
<div id="main">
    <div id="feed" class="feed-<?php echo $feedId; ?>" itemscope="video" itemtype="http://schema.org/VideoObject">
        <span itemprop="name" class="inactive"><?php echo $title; ?></span>
        <span class="inactive" itemprop="description"><?php echo $feed->getCleanDescription(); ?></span>
        <meta itemprop="thumbnailURL" content="<?php echo $feed->getThumbnail("high"); ?>" />
        <meta itemprop="embedURL" content="https://youtube.googleapis.com/v/<?php echo $id; ?>" />
        <iframe width="965" height="576" src="http://www.youtube.com/embed/<?php echo $id; ?>?enablejsapi=1&autoplay=1"
                frameborder="0"
                allowfullscreen></iframe>
    </div>
    <div id="info" class="module">
        <h1>Info</h1>

        <div class="moduleBody">
            <div id="share">
                <a class="fb-share openInWindow" title="Share this feed on Facebook!"
                   href="https://facebook.com/sharer.php?app_id=268335233334900&sdk=joey&u=http://www.leetfeed.com/feed/<?php echo $feedId; ?>&display=popup">Share</a>
                <a class="twitter-share openInWindow" title="Tweet about this feed on Twitter!"
                   href="https://twitter.com/intent/tweet?hashtags=leetfeed&original_referer=http://www.leetfeed.com&text=<?php echo $title . " leetfeed.com/feed/{$feedId}"; ?>&tw_p=tweetbutton&url=%2Ffeed%2F1268&via=leetfeed">Share</a>
            </div>
            <div id="title"><?php echo $title; ?></div>
            <div id="uploaded">by <a href="http://www.youtube.com/user/<?php echo $author; ?>" id="uploader"
                                     target="_blank"><?php echo $author; ?></a></div>
            <div id="rating" class="feedRating">
                <?php
                $account = $this->account();
                if ($account && $rating = $account->getRated($feedId)) {
                    if ($rating->getRating() == 1) {
                        $up = ' class=" disabled" ';
                        $down = '';
                    } else {
                        $up = '';
                        $down = ' class=" disabled" ';
                    }
                } else {
                    $up = '';
                    $down = '';
                }
                ?>
                <a href="<?php echo ($this->identity()) ? "#" : $this->url("login"); ?>" class="thumbUp"
                   <?php echo $up; ?>title="I like this feed!"><span class="icon"/></span>
                    Leet</a>
                <a href="<?php echo ($this->identity()) ? "#" : $this->url("login"); ?>"
                   class="thumbDown"<?php echo $down; ?> title="This feed is meh."><span class="icon"></span>Meh</a>

                <div id="total"><span class="icon"></span><span class="count"><?php echo $feed->getRating(); ?></span>
                </div>
            </div>
        </div>
    </div>
    <div class="module">
        <div class="hideToggle shadowed">Hide</div>
        <h1>Comments</h1>

        <div class="moduleBody">
            <?php if ($comments->count() > 0): ?>

                <ul id="commentList"  itemscope itemtype="http://schema.org/UserComments">
                    <?php foreach ($comments as $comment): ?>
                        <?php echo $this->partial("comment", array('comment' => $comment)); ?>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <div class="emptyComments">
                    <?php echo $this->translate("There are no comments on this feed yet, you can be the one to post first!"); ?>
                </div>
            <?php endif; ?>
            <div class="commentWrapper">
                <?php if (!$this->identity()) echo '<a href="' . $this->url('login', array('redirectUrl' => 'feed_' . $feedId)) . '">'; ?>
                <input type="text" id="addComment" placeholder="<?php echo $this->translate("Post a comment"); ?>"/>
                <?php if (!$this->identity()) echo '</a>'; ?>
                <div id="remainingChars">Remaining chars: <span class="number">150</span>/150</div>
            </div>
        </div>
    </div>
    <div id="related" class="module">
        <div class="hideToggle shadowed">Hide</div>
        <h1>Related Feeds</h1>

        <div class="moduleBody">
            <ul class="verticalFeedList">
                <?php
                foreach ($relatedFeeds as $feed) {
                    echo $this->partial("feed", array('feed' => $feed, 'isPremium' => false,'hasPrivileges' => $hasPrivileges));
                }
                ?>
            </ul>
        </div>
    </div>
</div>
