<?php
echo $this->doctype();
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
?>
<html lang="en">
<?php
// The layout's head
echo $this->partial("head", array('child' => $child));
?>
<body<?php echo ($child->bodyClass) ? ' class="' . $child->bodyClass .'"' : ''; ?>>
<noscript>
    <div id="nojs">
        <?php echo $this->translate("Please enable javascript for the site to work properly."); ?>
    </div>
</noscript>
<?php
$messages = $this->flashMessenger()->getMessages();
$clearMessages = array();
if (!empty($messages)) :
    ?>
    <div id="flash">
        <ul class="flashMessages">
            <?php foreach ($messages as $fMessage) : ?>
                <li><?php echo $fMessage; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<header>
    <div id="topWrapper">
        <div id="logo">
            <a href="<?php echo $this->url('home'); ?>"
               title="<?php echo $this->translate("Leetfeed"); ?>">Logo</a>
        </div>
        <?php
        // The website's navigation
        $file = $this->mobile() ? 'navigation_mobile' : 'navigation';
        echo $this->partial($file, array('child' => $child));
        ?>
    </div>
</header>
<div id="content">
<!--    --><?php //if (!isset($_COOKIE['facebookModerator'])): ?>
<!--        <div id="announcement" class="module" data-scope="facebookModerator">-->
<!--            <p>Are you going to be our new facebook page moderator? Feel free to apply at our <a-->
<!--                    href="--><?php //echo $this->url('contact'); ?><!--">contact page</a> using the subject title "Facebook-->
<!--                Application"!</p>-->
<!---->
<!--            <div class="remove">X</div>-->
<!--        </div>-->
<!--    --><?php //endif; ?>
    <?php if(!$child->noAds): ?>
    <div id="advertisement" class="module">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Leetfeed Adsense -->
        <ins class="adsbygoogle"
             style="display:inline-block;<?php echo $this->mobile() ? 'width:300px;height:250px' : 'width:728px;height:90px'; ?>"
             data-ad-client="ca-pub-6737088231270252"
             data-ad-slot="<?php echo $this->mobile() ? '5904753418' : '3425951819'; ?>"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
    <?php endif; ?>
    <?php echo $this->content; ?>
</div>
<?php
// The layout's footer
echo $this->partial("footer", array('child' => $child));
?>
</body>
</html>