<?php
/**
 * @var $comment \Feed\Entity\Comment
 */
$comment = $this->comment;
if ($comment):
    ?>
    <li itemtype="http://schema.org/Comment" itemscope="itemscope">
        <div class="comment-<?php echo $comment->getCommentId(); ?>">
            <div class="commentAccount"><span class="author"
                                              itemprop="author"><?php echo $comment->getAccount()->getUsername(); ?></span>
                :
            </div>
            <div class="commentBody" itemprop="text"><?php echo $this->escapeHtml($comment->getContent()); ?></div>
            <div class="commentTime">
                <time itemprop="dateCreated"
                      datetime="<?php echo $comment->getPostTime(); ?>"><?php echo (isset($isRecent) && $isRecent) ? "moments" : $comment->getTimeAgo(); ?>
                    ago
                </time>
            </div>
        </div>
    </li>
<?php endif; ?>