<?php
if ($isPremium) {
    $feed = $this->feed->getFeed();
}
$feedId = $feed->getFeedId();
$title = $this->escapeHtml(substr($feed->getTitle(), 0, 80));
$description = strlen($feed->getDescription()) > 100 ? substr($feed->getDescription(), 0, 100) . ".." : $feed->getDescription();
?>
<li class="feed-<?php echo $feedId; ?>" data-video-id="<?php echo $feed->getVideoId(); ?>">
    <div class="feedThumbnail">
        <?php
        echo '<a href="' . $this->url('feed/view', array('feedId' => $feedId)) . '" target="_top" title="' . $title . '">';
        echo '<img src="' . $feed->getThumbnail("medium") . '" />';
        echo '<div class="videoMask"></div>';
        echo '</a>';
        ?>
    </div>
    <div class="feedBody">
        <div class="feedHeader">
            <div class="feedTitle"><a
                    href="<?php echo $this->url('feed/view', array('feedId' => $feedId)); ?>"><?php echo $title; ?></a>
            </div>
            <div class="feedShare">
                <a class="fb-share openInWindow" title="Share this feed on Facebook!"
                   href="https://facebook.com/sharer.php?app_id=268335233334900&sdk=joey&u=http://www.leetfeed.com/feed/<?php echo $feedId; ?>&display=popup">Share</a>
                <a class="twitter-share openInWindow" title="Tweet about this feed on Twitter!"
                   href="https://twitter.com/intent/tweet?hashtags=leetfeed&original_referer=http://www.leetfeed.com&text=<?php echo $title . " leetfeed.com/feed/{$feedId}"; ?>&tw_p=tweetbutton&url=%2Ffeed%2F1268&via=leetfeed">Share</a>
            </div>
        </div>
        <div class="feedDescription">
            <?php echo nl2br($this->escapeHtml($description)); ?>
        </div>

    </div>
</li>