<?php
if ($isPremium) {
    $feed = $this->feed->getFeed();
}
if ($feed) {
    $feedId = $feed->getFeedId();
    $title = strlen($feed->getTitle()) > 55 ? substr($feed->getTitle(), 0, 53) . '..' : $feed->getTitle();
    ?>
    <li class="feed-<?php echo $feedId; ?>" data-video-id="<?php echo $feed->getVideoId(); ?>">
        <div class="feedTitle">
            <a
                href="<?php echo $this->url('feed/view', array('feedId' => $feedId)); ?>"
                title="<?php echo $feed->getTitle(); ?>"><?php echo $this->escapeHtml($title); ?></a>
            <?php if ($isPremium): ?>
                <a href="<?php echo $this->url('promote'); ?>" class="feedPremium" title="Premium"><img class="hoverable"
                        src="<?php echo $this->basePath('images/premium-icon.png'); ?>"/></a>
            <?php endif; ?>
        </div>
        <div class="feedThumbnail">
            <div id="preview-<?php echo $feedId; ?>"></div>
            <?php
            echo '<a href="' . $this->url('feed/view', array('feedId' => $feedId)) . '" target="_top" title="Click to watch the feed">';
            echo '<img src="' . $feed->getThumbnail("high") . '" />';
            echo '</a>';
            ?>
            <div class="videoMask"></div>
        </div>
        <div class="feedMeta">
            <div class="feedRating embed">
                <div class="total"><span class="icon"></span><span
                        class="count"><?php echo $feed->getRating(); ?></span>
                </div>
            </div>
            <div class="feedShare">
                <a class="fb-share openInWindow" title="Share this feed"
                   href="https://facebook.com/sharer.php?app_id=268335233334900&sdk=joey&u=http://www.leetfeed.com/feed/<?php echo $feedId; ?>&display=popup">Share</a>
                <a class="twitter-share openInWindow" title="Tweet about this feed"
                   href="https://twitter.com/intent/tweet?hashtags=leetfeed&original_referer=http://www.leetfeed.com&text=<?php echo $title . " leetfeed.com/feed/{$feedId}"; ?>&tw_p=tweetbutton&url=%2Ffeed%2F1268&via=leetfeed">Share</a>
            </div>
        </div>
        <?php if ($this->hasPrivileges): ?>
            <div class="feedDelete">
                <?php if($feed->getIsRelated() != 0): ?>
                <a href="<?php echo $this->url('feed/add', array('feedId' => $feedId, "type" => "exists")); ?>">Add to
                    front</a>
                <?php endif; ?>
                <a href="<?php echo $this->url('feed/remove', array('feedId' => $feedId, "type" => "delete")); ?>">Delete</a>
                <a href="<?php echo $this->url('feed/remove', array('feedId' => $feedId, "type" => "ignore")); ?>">Mark
                    as Ignored</a>
            </div>
        <?php endif; ?>
    </li>
<?php } ?>