<div id="main">
    <div class="module semiTransparentBackground">
        <h1>About Leetfeed</h1>
        <img class="centeredImage" src="<?php echo $this->basePath('images/leetfeed-medium.png'); ?>"/>
        <ol>
            <li>
                Q: What is Leetfeed?<br/>
                A: Leetfeed (LF) is a project that was made to kill the boredom of in and out of game League of Legends
                players. Let's say it's a minified version of Youtube, that includes only LoL feeds!
            </li>
            <li>
                Q: Can't I just go on Reddit or Youtube?
                A: Of course you can, the function of LF doesn't substitute the function of other sites in any way and
                the more you use this site, the easier you will understand this.
            </li>
        </ol>
    </div>
</div>