<div id="main">
    <div id="faq" class="module halfSized">
        <div class="moduleBody">
            <img class="centeredImage" src="<?php echo $this->basePath('images/leetfeed-medium.png'); ?>"/>
            <ol>
                <li>
                    <span class="question">What is Leetfeed?</span>
                    <span class="answer">Leetfeed (LF) is a project that was made to kill the boredom of in and out of game League of Legends players and make them improve their skills as well.</span>
                </li>
                <li>
                    <span class="question">Can't I just go on Reddit or Youtube?</span>
               <span class="answer">Of course you can, the function of LF doesn't substitute the function of other sites in any way and
                the more you use this site, the easier you will understand this.</span>
                </li>
                <li>
                    <span class="question">Okay.. so what <strong>really</strong> is the function of Leetfeed?</span>
                <span class="answer">The function of this site is simple.<br/>
                    It tries to find the best league of legends videos (feeds). This can be either from famous youtubers or pro players, as well as from the best and highest rated videos at the moment.
                    Moreover, you can link your league of legends accounts and it will suggest gameplays - tutorials based on your latest games and champions that you played.
                </span>
                </li>
                <li>
                    <span class="question">Why can't I upload my own videos?</span>
                    <span class="answer">Because as we said before, this site isn't Reddit/Youtube. You can upload them over there :)</span>
                </li>
                <li>
                    <span class="question">I found a video that isn't LoL related, you guys suck!!11</span>
                    <span class="answer">Oopsies our apologies! The generator gathers videos from youtube in a kinda automated way and some times may be wrong. Don't bully him :(</span>
                </li>
                <li>
                    <span class="question">What's up with the site's name?</span>
                    <span class="answer">Literally, the site's name means "elite feedback", that's where Leetfeed comes from!</span>
                </li>
                <li>
                    <span class="question">I want to help in some way, what can I do?</span>
                    <span class="answer">Any kind of help is always appreciated, you can contact us about anything you want at our <a
                            href="<?php echo $this->url("contact"); ?>">contact page </a>.</span>
                </li>
                <li>
                    <span class="question">Do you have any relationship to Riot Games?</span>
                    <span class="answer">This product is not endorsed, certified or otherwise approved in any way by Riot Games, Inc. or any of its affiliates.</span>
                </li>
            </ol>
        </div>
    </div>
</div>
