<div id="main">
    <div id="faq" class="module halfSized">
        <div class="moduleBody">
            <h1><?php echo $this->translate("Frequently Asked Questions"); ?></h1>
            <img class="centeredImage" src="<?php echo $this->basePath('images/leetfeed-medium.png'); ?>"
                 alt="<?php echo $this->translate("Leetfeed Logo"); ?>" width="200" height="200" />
            <ol>
                <li>
                    <span class="question shadowed">What is Leetfeed?</span>
                    <p class="answer">Leetfeed (LF) is a project that was made to kill the boredom of in and out of game <strong>League of Legends players</strong> and make them improve their skills as well.</p>
                </li>
                <li>
                    <span class="question shadowed">Okay.. so what really is the function of Leetfeed?</span>
                <p class="answer">The function of this site is simple.<br/>
                    It tries to find the best <strong>League of Legends videos</strong> (feeds). This can be either from famous youtubers or <strong>pro lcs players</strong>, as well as from the best and highest rated <strong>League of Legends videos</strong> at the moment.
                    Moreover, you can link your league of legends accounts and it will suggest <strong>League of Legends gameplay and tutorials</strong>  based on your latest games and champions that you played.
                </p>
                </li>
                <li>
                    <span class="question shadowed">Why can't I upload my own videos?</span>
                    <p class="answer">That's beyond the scope of Leetfeed, but we will consider it for the future.</p>
                </li>
                <li>
                    <span class="question shadowed">I found a related video that isn't League of Legends related, omg!</span>
                    <p class="answer">Oopsies our apologies! The generator gathers videos from youtube in a kinda automated way and some times may be wrong. Please be gentle!</p>
                </li>
                <li>
                    <span class="question shadowed">What's up with the site's name?</span>
                    <p class="answer">Literally, the site's name means "elite feedback", that's where Leetfeed comes from!</p>
                </li>
                <li>
                    <span class="question shadowed">I want to help in some way, what can I do?</span>
                    <p class="answer">Any kind of help is always appreciated, you can contact us about anything you want at our <a
                            href="<?php echo $this->url("contact"); ?>">contact page </a>.</p>
                </li>
                <li>
                    <span class="question shadowed">Do you have any relationship to Riot Games?</span>
                    <p class="answer">This product is not endorsed, certified or otherwise approved in any way by Riot Games, Inc. or any of its affiliates.</p>
                </li>
            </ol>
        </div>
    </div>
</div>
