<div id="main">
    <div id="faq" class="module semiTransparentBackground halfSized">
        <h1>Frequently Asked Questions</h1>
        <img class="centeredImage" src="<?php echo $this->basePath('images/leetfeed-medium.png'); ?>"/>
        <ol>
            <li>
                <span class="question">What is Leetfeed?</span>
                <span class="answer">Leetfeed (LF) is a project that was made to kill the boredom of in and out of game League of Legends
                players. Let's say it's a minified version of Youtube, that includes only League of Legends related video feeds!</span>
            </li>
            <li>
                <span class="question">Can't I just go on Reddit or Youtube?</span>
               <span class="answer">Of course you can, the function of LF doesn't substitute the function of other sites in any way and
                the more you use this site, the easier you will understand this.</span>
            </li>
            <li>
                <span class="question">Okay.. so what <strong>really</strong> is the function of Leetfeed?</span>
                <span class="answer">The function of this site is simple.<br />
                    It tries to find the best videos on youtube from famous youtubers/pro players as well as the top rated videos on LF.<br />
                    Moreover, it has a "random" button that finds a totally new feed that you haven't directly watched on this website before, because that would be lame!<br />
                    Features are and will be added regularly, depending on the people's choices!
                </span>
            </li>
            <li>
                <span class="question">Why can't I upload my own videos?</span>
                <span class="answer">Because as we said before, this site isn't Reddit/Youtube. You can upload them over there :)</span>
            </li>
            <li>
                <span class="question">I found a video that isn't LoL related, you guys suck!!11</span>
                <span class="answer">Oopsies our apologies! The generator gathers videos from youtube in a kinda automated way and some times may be wrong. Don't bully him :(</span>
            </li>
            <li>
                <span class="question">What's up with the site's name?</span>
                <span class="answer">Literally, the site's name means "elite feedback", that's where Leetfeed comes from! It's pronounced as "litfid".</span>
            </li>
            <li>
                <span class="question">I want to help in some way, what can I do?</span>
               <span class="answer">Any kind of help is always appreciated, you can contact us about anything you want at our <a href="<?php echo $this->url("contact"); ?>">contact page </a>.</span>
            </li>
        </ol>
    </div>
</div>