<div id="main">

    <div class="module">

        <div class="moduleBody">
            <ul data-page="1" data-total="<?php echo $feedPages; ?>" id="top-feeds"
                class="verticalFeedList expandable">
                <?php
                foreach ($premiumFeeds as $feed) {
                    echo $this->partial("feed", array('feed' => $feed, 'isPremium' => true, 'hasPrivileges' => $hasPrivileges));
                }
                foreach ($feeds as $feed) {
                    echo $this->partial("feed", array('feed' => $feed, 'isPremium' => false, 'hasPrivileges' => $hasPrivileges));
                }
                ?>
            </ul>
        </div>
    </div>
</div>