<div id="main">
    <div id="promote" class="module">
        <div class="moduleBody halfSized">
            <h1><?php echo $this->translate("Promote Your League of Legends Videos"); ?></h1>
            <img class="centeredImage" src="<?php echo $this->basePath('images/leetfeed-medium.png'); ?>"
                 alt="<?php echo $this->translate("Leetfeed Logo"); ?>" width="200" height="200"/>

            <p><?php echo $this->translate("Are you a <strong>League of Legends video</strong> / <strong>content</strong> creator? Do you want to promote your <strong>videos</strong> even more? <br /> Then <strong>keep reading</strong>, this is for you!"); ?></p>

            <p>
                <?php echo $this->translate("Here at Leetfeed, we can promote and advertise your <strong>League of Legends videos</strong> by placing them in the <strong>front page of our website</strong>, so that they will get the most views possible."); ?>
                <br/>
            </p>
            <img src="<?php echo $this->basePath('images/promoted.jpg'); ?>"
                 alt="<?php echo $this->translate('promotion image'); ?>"
                 width="450"
                 class="bordered shadowed"
                 height="327"/>

            <p>
                <?php
                echo $this->translate("They will remain at the top of the front page's feed list for <strong>as long as it is agreed</strong>, without any chances of them getting lost among all the other videos. <br />
                    Moreover, we will provide you with email feedback on how many views they are getting on our page, so that you know how well they are doing.<br/>
                    The money we receive are used to support the website, so you are helping us in that part as well :) <br />
                    ");
                ?>
                <?php
                echo $this->translate("For more info you can contact us at") . ' <a href="mailto:promote@leetfeed.com">promote@leetfeed.com</a> ' . $this->translate("(preferred way) ");
                echo $this->translate("or through our") . ' <a href="' . $this->url('contact') . '">' . $this->translate("contact page.") . '</a>';
                ?>
            </p>
        </div>
    </div>
</div>